package driver

import "github.com/thingio/edge-device-std/models"

var Opcua = &models.Protocol{
	ID:       "opc_ua",
	Name:     "OPCUA",
	Desc:     "OPCUA",
	Category: "tick",
	Language: "ch",
	SupportFuncs: []string{
		"property",
		"event",
		"method",
	},
	AuxProps: []*models.Property{
		{
			Id: 	 "display_name",
			Desc: 	 "显示名称",
			Name: 	 "节点ID",
			Type:	 "string",
			UIStyle: "input",
			Default:  "",
			Required: true,
		},
	},
	DeviceProps: []*models.Property{
		{
			Id: "endpoint",
			Desc: "OPC UA Endpoint URL",
			Name: "服务地址",
			Type: "string",
			UIStyle: "input",
			Default: "opc.tcp://localhost:4840",
			Required: true,
		},
		{
			Id: "node_path",
			Name: "设备路径",
			Desc: "设备节点所在绝对路径,如Objects/demo_device",
			Type: "string",
			UIStyle: "input",
			Default: "Objects/demo_device",
			Required: true,
		},
		{
			Id: "interval",
			Name: "采集间隔",
			Desc: "设备属性数据全局采集间隔",
			Type: "string",
			UIStyle: "input",
			Required: true,
			Default: "500ms",
		},
		{
			Id: "auto",
			Name: "自动获取属性",
			Desc: "是否将自动获取的属性写回产品定义",
			Type: "bool",
			UIStyle: "selector",
			Range: "true@@是,false@@否",
			Required: true,
			Default: "false",
		},
		{
			Id: "write_back",
			Name: "更新产品",
			Desc: "是否将自动获取的属性写回产品定义",
			Type: "bool",
			UIStyle: "selector",
			Range: "true@@是,false@@否",
			Required: false,
			Default: "false",
			Precondition: "auto==true",
		},
		{
			Id: "sc_policy",
			Desc: "Security Policy URL or one of None, Basic128Rsa15, Basic256, Basic256Sha256",
			Name: "安全策略",
			Type: "string",
			UIStyle: "selector",
			Range: "None@@无,Basic128Rsa15@@Basic128Rsa15,Basic256@@Basic256,Basic256Sha256@@Basic256Sha256",
			Default: "None",
			Required: true,
		},
		{
			Id: "sc_mode",
			Desc: "Security Mode: one of None, Sign, SignAndEncrypt",
			Name: "安全模式",
			Type: "string",
			UIStyle: "selector",
			Range: "None@@无,Sign@@Sign,SignAndEncrypt@@SignAndEncrypt",
			Default: "None",
			Required: true,
		},
		{
			Id: "username",
			Name: "用户名",
			Type: "string",
			UIStyle: "input",
			Required: false,
		},
		{
			Id: "password",
			Name: "密码",
			Type: "string",
			UIStyle: "password",
			Required: false,
		},
		{
			Id: "cert_file",
			Name: "数字证书",
			Desc: "数字证书文件所在路径",
			Type: "string",
			UIStyle: "input",
			Required: false,
		},
		{
			Id: "key_file",
			Name: "密钥证书",
			Desc: "密钥证书文件所在路径",
			Type: "string",
			UIStyle: "input",
			Required: false,
		},
	},
}